from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

try:  # pragma: no cover - import path depends on execution mode
    from gqe.data.fragmentation import (
        build_active_space_spec,
        build_fragment_records,
        load_fragment_plan,
    )
except ImportError:  # pragma: no cover - direct script execution fallback
    from fragmentation import (  # type: ignore[no-redef]
        build_active_space_spec,
        build_fragment_records,
        load_fragment_plan,
    )


def _load_geometry_from_value(value: str | Path) -> list[list[Any]]:
    path = Path(value)
    if path.exists():
        payload = json.loads(path.read_text(encoding="utf-8"))
    else:
        payload = json.loads(str(value))
    if not isinstance(payload, list):
        raise ValueError("Geometry must be a JSON list of [symbol, [x, y, z]] entries.")
    return payload


def _load_config_molecule(config_path: Path, molecule_name: str | None) -> tuple[dict[str, Any], dict[str, Any]]:
    with config_path.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    molecules = list(cfg.get("dataset", {}).get("molecules", []))
    if not molecules:
        raise ValueError("The provided config does not contain any molecules.")

    if molecule_name is None:
        if len(molecules) != 1:
            raise ValueError(
                "The config contains multiple molecules, so --molecule is required to select one."
            )
        return cfg, dict(molecules[0])

    for molecule in molecules:
        if molecule.get("name") == molecule_name:
            return cfg, dict(molecule)

    available = ", ".join(str(m.get("name", "<unnamed>")) for m in molecules)
    raise ValueError(f"Could not find molecule {molecule_name!r}. Available molecules: {available}")


def _resolve_fragment_plan(
    molecule: dict[str, Any],
    config_fragment_plan: list[dict[str, Any]] | None,
) -> list[dict[str, Any]]:
    fragments = list(molecule.get("fragments", []))
    if config_fragment_plan:
        fragments.extend(config_fragment_plan)
    return fragments


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare fragment and active-space plans for a molecule.")
    parser.add_argument("--config", type=Path, default=None, help="Optional experiment YAML containing molecule definitions.")
    parser.add_argument("--molecule", type=str, default=None, help="Molecule name to select from --config.")
    parser.add_argument("--name", type=str, default=None, help="Explicit molecule name when not using --config.")
    parser.add_argument("--geometry-json", type=str, default=None, help="Inline JSON geometry list.")
    parser.add_argument("--geometry-file", type=Path, default=None, help="Path to a JSON file with geometry.")
    parser.add_argument("--basis", type=str, default=None, help="Basis set name when not using --config.")
    parser.add_argument("--charge", type=int, default=0, help="Molecular charge when not using --config.")
    parser.add_argument("--multiplicity", type=int, default=1, help="Spin multiplicity when not using --config.")
    parser.add_argument(
        "--active-space-mode",
        type=str,
        default=None,
        help="Active-space policy: full, freeze_core/core_valence, explicit.",
    )
    parser.add_argument("--n-active-electrons", type=int, default=None)
    parser.add_argument("--n-active-orbitals", type=int, default=None)
    parser.add_argument("--n-core-orbitals", type=int, default=None)
    parser.add_argument("--occupied-indices", type=str, default=None)
    parser.add_argument("--active-indices", type=str, default=None)
    parser.add_argument(
        "--fragment-plan",
        type=Path,
        default=None,
        help="Optional JSON fragment plan generated by this script or authored by hand.",
    )
    parser.add_argument("--out", type=Path, required=True, help="Output JSON path for the fragment plan.")
    args = parser.parse_args()

    config = None
    molecule: dict[str, Any]
    if args.config is not None:
        config, molecule = _load_config_molecule(args.config, args.molecule)
        dataset = config.get("dataset", {})
        name = str(molecule.get("name", args.molecule or "molecule"))
        geometry = list(molecule.get("geometry", []))
        basis = str(molecule.get("basis", dataset.get("basis", args.basis or "sto-3g")))
        charge = int(molecule.get("charge", args.charge))
        multiplicity = int(molecule.get("multiplicity", args.multiplicity))
    else:
        if args.geometry_json is not None:
            geometry = _load_geometry_from_value(args.geometry_json)
        elif args.geometry_file is not None:
            geometry = _load_geometry_from_value(args.geometry_file)
        else:
            raise ValueError("Provide either --config or one of --geometry-json/--geometry-file.")
        if args.basis is None:
            raise ValueError("--basis is required when --config is not provided.")
        name = str(args.name or "molecule")
        basis = str(args.basis)
        charge = int(args.charge)
        multiplicity = int(args.multiplicity)
        molecule = {
            "name": name,
            "geometry": geometry,
            "basis": basis,
            "charge": charge,
            "multiplicity": multiplicity,
        }

    active_space_cfg = dict(molecule.get("active_space", {}))
    if args.active_space_mode is not None:
        active_space_cfg["mode"] = args.active_space_mode
    if args.n_active_electrons is not None:
        active_space_cfg["n_active_electrons"] = args.n_active_electrons
    if args.n_active_orbitals is not None:
        active_space_cfg["n_active_orbitals"] = args.n_active_orbitals
    if args.n_core_orbitals is not None:
        active_space_cfg["n_core_orbitals"] = args.n_core_orbitals
    if args.occupied_indices is not None:
        active_space_cfg["occupied_indices"] = args.occupied_indices
    if args.active_indices is not None:
        active_space_cfg["active_indices"] = args.active_indices

    active_space = build_active_space_spec(
        **active_space_cfg,
        geometry=geometry,
        basis=basis,
        charge=charge,
        multiplicity=multiplicity,
    )

    fragment_plan_records: list[dict[str, Any]] = []
    if args.fragment_plan is not None:
        fragment_plan_records = load_fragment_plan(args.fragment_plan)

    fragments = _resolve_fragment_plan(molecule, fragment_plan_records)
    fragment_records = build_fragment_records(
        parent_name=name,
        geometry=geometry,
        fragments=fragments,
        charge=charge,
        multiplicity=multiplicity,
        basis=basis,
        active_space=active_space,
    )

    payload = {
        "name": name,
        "geometry": geometry,
        "basis": basis,
        "charge": charge,
        "multiplicity": multiplicity,
        "active_space": active_space.as_dict(),
        "fragment_count": len(fragment_records),
        "fragments": fragment_records,
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    print(f"Wrote fragment plan to: {args.out}")


if __name__ == "__main__":
    main()
